---
- name: CentOS | Install kubernetes node
  yum:
    pkg=kubernetes-node
    state=latest
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  notify:
    - restart daemons
