- name: Fedora | Install kubernetes node
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: kubernetes-node
    state: latest
    enablerepo: "updates-testing"
  environment: "{{ proxy_env | default('') }}"
  notify:
    - restart daemons
