- name: Generic | Install kubernetes node
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: kubernetes-node
    state: latest
  environment: "{{ proxy_env | default('') }}"
  notify:
    - restart daemons
