---
- name: Install docker custom repository
  template: src=dockerrepo.repo.j2 dest=/etc/yum.repos.d/dockerrepo.repo

- name: Install docker engine
  yum: name={{ item }} state=latest
  with_items:
    - {{ docker_package_name }}
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
