---
- name: Override docker config file directory for Debian
  set_fact:
    docker_config_dir: "/etc/default"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

# TODO(jchaloup): This needs to go under install.yml, it is installation source dependent
- name: Create config file directory
  file: path={{ docker_config_dir }} state=directory
  tags: install

- name: Install docker
  include: install.yml
  tags: install

- set_fact:
    docker_use_systemd_unit: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 7

- include: systemd-unit.yml
  when: docker_use_systemd_unit

- include: systemd-unit.yml
  when: not docker_use_systemd_unit

- name: Enable Docker
  service: name=docker enabled=yes
  notify:
    - start docker
