---
- name: Create docker config dir exists
  file: path={{ docker_config_dir }} state=directory
  tags: install

- name: Create docker service.d dir exists
  file: path={{ docker_dropin_dir }} state=directory
  tags: install

- name: Configure docker dropin
  template: src=systemd/docker.conf.j2 dest={{ docker_dropin_dir }}/docker.conf
  notify:
    - reload systemd
    - restart docker
  tags: configure

- name: Configure docker EnvironmentFile
  template: src=systemd/docker.j2 dest={{ docker_config_dir }}/docker
  notify:
    - reload systemd
    - restart docker
  tags: configure

- name: Configure docker network docker EnvironmentFile
  template: src=systemd/docker-network.j2 dest={{ docker_config_dir }}/docker-network
  notify:
    - reload systemd
    - restart docker
  tags: configure

- name: Determine if thinpool exists
  stat: path=/dev/mapper/docker-thinpool
  register: thin_pool_check
  changed_when: false
  always_run: yes
  tags: configure

- name: Configure docker network docker storage EnvironmentFile
  template: src=systemd/docker-storage.j2 dest={{ docker_config_dir }}/docker-storage
  notify:
    - reload systemd
    - restart docker
  when: thin_pool_check.stat.exists
  tags: configure
